### ISSUE TITLE
Refactor tokens-related test suites to be slimmer

### ISSUE THREAD

**Issue by lepidotteri** [ARM-Finance/kingmaker#7]
While the more tests the better, generally, I do think that there is a lot of redundancy in a few test suites that could be merged with one another, this is particularly true for those found here:

- https://github.com/ARM-Finance/kingmaker/blob/test/token/protocol/test/token/TestCollateralizedEther.ts
- https://github.com/ARM-Finance/kingmaker/blob/test/token/protocol/test/token/TestCollateralizedERC20.ts

The goal is to shrink the # of test suites while maintaining the current contracts coverage more or less unchanged

**Comment by SHA-2048** [comment]
Reading the contracts I was thinking maybe the CollaterizedEther should not exist and rather rely the ETH->WETH in that case to make things more composable. 

So whenever ETH is user maybe the contract would just wrap if first and then apply the ERC20 logic. Or is it even worth to include the wrap logic here and just support only ERC20s

What do you think @lepidotteri ?

**Comment by lepidotteri** [comment]
> Reading the contracts I was thinking maybe the CollaterizedEther should not exist and rather rely the ETH->WETH in that case to make things more composable. 
> 
> 
> 
> So whenever ETH is user maybe the contract would just wrap if first and then apply the ERC20 logic. Or is it even worth to include the wrap logic here and just support only ERC20s
> 
> 
> 
> What do you think @lepidotteri ?

- This is my fault for not being quicker in adding the (Diamond standard-compliant) governance contracts, I will try to do it today still even though I'm at the lake atm. once that's done, hopefully the discussion around this will become clearer to us both.

![image](https://user-images.githubusercontent.com/45174270/107879695-ac71d800-6eda-11eb-8bfd-3064c6884934.jpeg)

**Comment by SHA-2048** [comment]
ok enjoy. I started reading about the standard

**Comment by lepidotteri** [comment]
> ok enjoy. I started reading about the standard

https://louper.dev/

newly released tool useful for displaying any Diamond contracts inner workings

e.g. https://louper.dev/?address=0x10e138877df69Ca44Fdc68655f86c88CDe142D7F
